POST http://localhost:8080/signup
Content-Type: application/json

{
  "email": "user1@test.com",
  "password": "dummypw"
}

###

GET http://localhost:8080/csrf

###

POST http://localhost:8080/login
Content-Type: application/json
X-Csrf-Token: D6OUko3e5BbCpn2VIbkVQ60WgmjYqlOt

{
  "email": "user1@test.com",
  "password": "dummypw"
}

###

POST http://localhost:8080/logout
Content-Type: application/json

{
  "email": "user1@test.com",
  "password": "dummypw"
}

###


GET http://localhost:8080/tasks
Content-Type: application/json

###

POST http://localhost:8080/tasks
Content-Type: application/json
X-Csrf-Token: D6OUko3e5BbCpn2VIbkVQ60WgmjYqlOt

{
  "title": "task1"
}

###

GET http://localhost:8080/tasks/1
Content-Type: application/json

###

PUT http://localhost:8080/tasks/1
Content-Type: application/json

{
  "title": "task1 updated"
}

###

DELETE http://localhost:8080/tasks/1
Content-Type: application/json

###
